server:
  port: 8770

spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200 # 指明es地址
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: tao200131
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    #虚拟host 可以不设置,使用server默认host
    virtual-host: JCcccHost